articles = [
    {
        "id": "52a3bfb4657f036025253ea51edd9249",
        "title": "Four States Game Night Final Scores — Week 2",
        "description": "Week 2 of high school football in the Four States is in the books! See below final scores from an abundance of area programs.",
        "url": "https://sports.yahoo.com/articles/four-states-game-night-final-053700897.html",
        "source": {"name": "Yahoo! News", "url": "https://news.yahoo.com"},
        "published_at": "2026-09-05T11:37:00+06:00",
        "category": ["sports", "breaking"],
        "tags": [
            "high school game night",
            "high school football",
            "sports connection",
            "sports",
            "local sports",
            "game night",
            "high school football game night",
        ],
    },
    {
        "id": "6d47fae7ae848b06f82703addde83804",
        "title": "France: pumpkin seeds recalled after more than 80 salmonella cases",
        "description": "Grouped cases of Salmonella Enteritidis from a single strain have been detected in France. Health officials suspect pumpkin seeds from Lot-et-Garonne sold mainly at Grand Frais.",
        "url": "http://www.euronews.com/health/2026/09/05/france-pumpkin-seeds-recalled-after-more-than-80-salmonella-cases",
        "source": {"name": "Euronews", "url": "https://www.euronews.com"},
        "published_at": "2026-09-05T11:36:54+06:00",
        "category": ["top", "crime"],
        "tags": ["france", "salmonella", "public health"],
    },
    {
        "id": "57fba4e9544ce32ea76ab01f75be7b79",
        "title": "ETMarkets Smart Talk | Don't judge India by Nifty's 21x PE; stock-level valuations still offer opportunities: Emkay Investment Managers: Kashyap Javeri",
        "description": "Kashyap Javeri suggests India’s market valuation premium is misleading due to index concentration. He highlights strong mid- and small-cap earnings growth, reliable SIP inflows, and easing FPI selling, while cautioning against risks like rising crude prices and currency fluctuations.",
        "url": "https://economictimes.indiatimes.com/markets/expert-view/etmarkets-smart-talk-dont-judge-india-by-niftys-21x-pe-stock-level-valuations-still-offer-opportunities-emkay-investment-managers-kashyap-javeri/articleshow/133789173.cms",
        "source": {
            "name": "The Economic Times",
            "url": "https://economictimes.indiatimes.com",
        },
        "published_at": "2026-09-05T11:36:41+06:00",
        "category": ["business"],
        "tags": [
            "emerging markets",
            "emkay investment managers",
            "small-cap stocks",
            "systematic investment plan",
            "indian stock market",
            "nifty 100",
            "pe multiples",
            "earnings growth",
            "fpi flows",
            "mid-cap stocks",
        ],
    },
    {
        "id": "ce20e8734a86d1173b94e1f579a8faa2",
        "title": "Keyaa Banerji, who won silver with 140kg deadlift, subjected to online horror: ‘Feed flooded with AI pictures’",
        "description": "Keyaa Banerji, who recently won a silver medal, opens up about facing online abuse. Here's what she shared on social media.",
        "url": "https://www.hindustantimes.com/sports/others/keyaa-banerji-who-won-silver-with-140kg-deadlift-subjected-to-online-horror-feed-flooded-with-ai-pictures-101788585644183.html",
        "source": {"name": "Hindustan Times", "url": "http://www.hindustantimes.com"},
        "published_at": "2026-09-05T11:36:35+06:00",
        "category": ["top", "technology"],
        "tags": ["latest"],
    },
    {
        "id": "7d36748443718df36cee6767753f4f03",
        "title": "Vertiv: The Backbone Of AI Revolution",
        "description": "Vertiv (VRT) could have more upside despite a 100%+ run—AI/data center tailwinds, Mag 7 capex catalysts, valuation, and risks.",
        "url": "https://seekingalpha.com/article/4943280-vertiv-the-backbone-of-ai-revolution",
        "source": {"name": "Seeking Alpha", "url": "https://seekingalpha.com"},
        "published_at": "2026-09-05T11:36:34+06:00",
        "category": ["business"],
        "tags": ["the j thesis", "vrt:ca", "vrt"],
    },
    {
        "id": "71d554a265929b58291e024f3dd6bb6b",
        "title": "Asif says devolution of power is 'inevitable', accuses PPP of having contradictory stance on new provinces",
        "description": "Defence Minister Khawaja Asif has said that the devolution of power is “inevitable”, while also accusing the PPP of having a contradictory stance on the issue of new provinces.",
        "url": "https://www.dawn.com/news/2027666/asif-says-devolution-of-power-is-inevitable-accuses-ppp-of-having-contradictory-stance-on-new-provinces",
        "source": {"name": "Dawn", "url": "https://www.dawn.com"},
        "published_at": "2026-09-05T11:36:25+06:00",
        "category": ["top", "politics"],
        "tags": ["pakistan"],
    },
    {
        "id": "9603b1beb094b7be3d118c43fd3c8cb2",
        "title": "The Good, The Bad, and The Ugly: Stanford Cardinal 2026 Edition",
        "description": "Miami started the 2026 season with a blowout win over Stanford. As it should be.",
        "url": "https://sports.yahoo.com/articles/good-bad-ugly-stanford-cardinal-053620586.html",
        "source": {"name": "Yahoo! News", "url": "https://news.yahoo.com"},
        "published_at": "2026-09-05T11:36:20+06:00",
        "category": ["sports", "breaking"],
        "tags": [
            "2026",
            "malachi toney",
            "miami hurricanes football",
            "miami",
            "stanford",
            "darian mensah",
            "toney",
            "stanford stadium",
        ],
    },
    {
        "id": "4f0a95eba7757a7e89622902ac9563d1",
        "title": "Death threats reported in red route row",
        "description": 'A cabinet member says colleagues have been targeted in an "abhorrent" social media campaign.',
        "url": "https://ca.news.yahoo.com/death-threats-reported-red-route-053616281.html",
        "source": {"name": "Yahoo! News", "url": "https://news.yahoo.com"},
        "published_at": "2026-09-05T11:36:16+06:00",
        "category": ["sports"],
        "tags": ["news"],
    },
    {
        "id": "0a8ed993a2afcdb8283a47c74c98f7d0",
        "title": "Delhi rains: IndiGo, Akasa Air issue travel advisory as weather conditions disrupt flight ops at IGI Airport",
        "description": "Heavy rain lashed Delhi and nearby areas on Saturday morning. IndiGo and Akasa Air issued advisories for potential flight disruptions. Delhi Airport operations remained normal while authorities monitored the weather closely. Moderate showers brought down the minimum temperature across the national capital. Traffic movement faced disruptions due to waterlogging and event rehearsals.",
        "url": "https://economictimes.indiatimes.com/industry/transportation/airlines-/-aviation/delhi-airport-advisory-travel-flight-disruptions-indira-gandhi-international-akasa-air-spicejet-indigo-air-india-waterlogging-weather-today-heavy-rain-imd-orange-alert/articleshow/133789031.cms",
        "source": {
            "name": "The Economic Times",
            "url": "https://economictimes.indiatimes.com",
        },
        "published_at": "2026-09-05T11:36:15+06:00",
        "category": ["business"],
        "tags": [
            "delhi airport",
            "air india",
            "delhi flight operations",
            "indigo",
            "today weather delhi",
            "delhi weather today",
            "delhi weather",
            "weather delhi",
            "delhi travel advisory",
            "delhi rain today",
        ],
    },
    {
        "id": "2c443939955c5d58fc21d1ccbf075aa0",
        "title": "POCO X8 and POCO X8 Power launched in India with up to 10,000mAh battery, Snapdragon chipsets and 1.5K AMOLED display",
        "description": "POCO has expanded its X-series lineup in India with the launch of the POCO X8 and POCO X8 Power. The new smartphones feature large Silicon-Carbon batteries, Snapdragon processors, 1.5K AMOLED displays, 50MP OIS cameras, Android 16-based HyperOS 3, and up to six years of software support.",
        "url": "https://www.moneycontrol.com/technology/poco-x8-and-poco-x8-power-launched-in-india-with-up-to-10-000mah-battery-snapdragon-chipsets-and-1-5k-amoled-display-article-14023224.html",
        "source": {"name": "Moneycontrol", "url": "https://www.moneycontrol.com"},
        "published_at": "2026-09-05T11:36:13+06:00",
        "category": ["top", "technology"],
        "tags": ["poco x8 launch"],
    },
]
